spring.application.name=EmployeeManagement

server.port = 8002

#database connection
spring.datasource.url=jdbc:mysql://localhost:3306/cts
spring.datasource.username=root
spring.datasource.password=Salunke@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
#hibernate properties 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#For Actuator , here * is for all endpoints, we can go for health,bean and other
management.endpoints.web.exposure.include=*

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
# 
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create
#server.port=1234